### ISSUE TITLE
Library GLU missing in some installations

### ISSUE THREAD

**Issue by maxspahn** [maxspahn/gym_envs_planar#34]
Traceback (most recent call last):
  File "/home/nagrawal/.cache/pypoetry/virtualenvs/plannerbenchmark-nPaI4okZ-py3.8/lib/python3.8/site-packages/gym/envs/classic_control/rendering.py", line 27, in <module>
    from pyglet.gl import *
  File "/home/nagrawal/.cache/pypoetry/virtualenvs/plannerbenchmark-nPaI4okZ-py3.8/lib/python3.8/site-packages/pyglet/gl/__init__.py", line 95, in <module>
    from pyglet.gl.gl import *
  File "/home/nagrawal/.cache/pypoetry/virtualenvs/plannerbenchmark-nPaI4okZ-py3.8/lib/python3.8/site-packages/pyglet/gl/gl.py", line 45, in <module>
    from pyglet.gl.lib import link_GL as _link_function
  File "/home/nagrawal/.cache/pypoetry/virtualenvs/plannerbenchmark-nPaI4okZ-py3.8/lib/python3.8/site-packages/pyglet/gl/lib.py", line 149, in <module>
    from pyglet.gl.lib_glx import link_GL, link_GLU, link_GLX
  File "/home/nagrawal/.cache/pypoetry/virtualenvs/plannerbenchmark-nPaI4okZ-py3.8/lib/python3.8/site-packages/pyglet/gl/lib_glx.py", line 46, in <module>
    glu_lib = pyglet.lib.load_library('GLU')
  File "/home/nagrawal/.cache/pypoetry/virtualenvs/plannerbenchmark-nPaI4okZ-py3.8/lib/python3.8/site-packages/pyglet/lib.py", line 164, in load_library
    raise ImportError('Library "%s" not found.' % names[0])
ImportError: Library "GLU" not found.

**Comment by maxspahn** [comment]
It seems like installing 
`sudo apt instal libgl1-mesa-dev freeglut3`
solvers the problem. 
However, I am not able to reproduce this issue in a docker, so it is hard to tell.

**Comment by maxspahn** [comment]
There are multiple threads in openai-gym:
https://github.com/openai/gym/issues/2478
https://stackoverflow.com/questions/40195740/how-to-run-openai-gym-render-over-a-server

**Comment by maxspahn** [comment]
A known fix to this problem is `sudo apt install python-opengl`
